# Numpy

### What is an array?
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

### What is Numpy?
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

In [1]:
# Import the package
import numpy as np

In [2]:
#creating an array
L=[1,2,3,4,5]
arr=np.array(L)
#list passed

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape
# 1-D array has only 1 value in shape,i.e, its number of elements

(5,)

In [6]:
#(name_of_array,index,elelemnt)
arr=np.insert(arr,5,int(40))
arr

array([ 1,  2,  3,  4,  5, 40])

In [7]:
arr=np.delete(arr,3)     # delete(array,index)
arr

array([ 1,  2,  3,  5, 40])

In [8]:
# Creating 2-D array
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr1=np.array([lst1,lst2,lst3])

In [9]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [10]:
arr1.shape
#(rows,columns)

(3, 5)

In [11]:
# accessing element through indexing
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [12]:
arr1[(1,2)]   # prints element place at row=1,column=2

4

In [13]:
arr1[:,1]    # row=all, column=1

array([2, 3, 4])

In [14]:
arr1[1:,1:3]    # row= 1-last,  column=1,2 as 3 is excluded

array([[3, 4],
       [4, 5]])

In [15]:
arr2=np.array([1,2,"hi"])   # numpy holds same dtype elements, so it converts each element into string
arr2

array(['1', '2', 'hi'], dtype='<U11')

# Functions in Numpy

### arange

In [16]:
arr3=np.arange(4,40,2)   # arange(start,end,step)
arr3

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38])

In [17]:
#zeros-make a array having all elements zero
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
#ones - make a numpy array having all ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
#identity - make a numpy array having only diagonal elements ones
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
#linspace - LINEAR SPACE- having equally linear space in all elements
arr7=np.linspace(5,20,5)    #linspace(start,end,number of elements)
arr7

array([ 5.  ,  8.75, 12.5 , 16.25, 20.  ])

In [21]:
arr8=np.linspace(1,10,30)

In [22]:
arr8

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [23]:
arr8.size

30

In [24]:
arr8.ndim

1

In [25]:
arr8.itemsize

8

In [26]:
arr8.dtype

dtype('float64')

In [27]:
arr8.astype(int)

array([ 1,  1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,  5,  5,
        6,  6,  6,  7,  7,  7,  8,  8,  8,  9,  9,  9, 10])

# List vs Numpy

In [28]:
list1=range(1000)
arr12=np.arange(1000)

In [29]:
import sys

In [30]:
print(sys.getsizeof(list1)*len(list1))

48000


In [31]:
print(arr12.size*arr.itemsize) # array taking less memory

4000


In [32]:
import time

In [33]:
x=range(100000000)
y=range(100000000,200000000)

start_time=time.time()
c=[x+y for x,y in zip(x,y)]
print(time.time()-start_time)

21.830798387527466


In [34]:
a=np.arange(100000000)
b=np.arange(100000000,200000000)
start_time=time.time()
c=a+b
print(time.time()-start_time)  #how fast is  numpy than array

2.5405328273773193


### Created by Sarthak Aggarwal
