In [1]:
import cv2

In [9]:
img=cv2.imread("PV/linkedin.jpg",0)

## 1) Representation of an image

In [3]:
print(img)

[[85 85 85 ... 85 85 85]
 [85 85 85 ... 85 85 85]
 [85 85 85 ... 85 85 85]
 ...
 [85 85 85 ... 85 85 85]
 [85 85 85 ... 85 85 85]
 [85 85 85 ... 85 85 85]]


In [4]:
type(img)

numpy.ndarray

Image is actually a numpy array
- OpenCV extracts the pixels from the image and load it in numpy

In [5]:
cv2.imshow("Image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
img.shape

(398, 398)

shape is (x,y,z)
- x= no. of rows/ height of the image
- y= no. of columns/ width of image
- z= no. of channels - no. of values storing each pixel

In [8]:
img2=cv2.imread("PV/linkedin.jpg",-1)

In [10]:
img2.shape

(398, 398, 3)

- 3 channels is due to the colour- BGR
- standard is RGB but openCV uses BGR,i.e, blue green red
- [x,y,z] pixel represents x amt of blue, y amt. of green and z amt. of red in the pixel
- 0-zero, 255-one.....range is (0-255)
- [255,0,0] represents all blue and none green n red
- [122,0,0] represents some blue and no green n red

## 2) Accessing pixel values

In [12]:
print(img2[0])

[[195 102  11]
 [195 102  11]
 [195 102  11]
 ...
 [195 102  11]
 [195 102  11]
 [195 102  11]]


In [13]:
print(img2[100][100])

[252 250 250]


In [14]:
print(img2[50][100])

[195 102  11]


## 3) Changing pixel values

In [15]:
cv2.imshow("Image",img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
img2.shape

(398, 398, 3)

In [17]:
# if you want to double the size then fx=2,fy=2 and if half then fx=0.5,fy=0.5
img3=cv2.resize(img2,(0,0),fx=2,fy=2)
cv2.imshow("Image1",img3)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
img3.shape

(796, 796, 3)

- Doubling the size of image will double rows and columns

In [19]:
import random

In [20]:
for i in range(100):
    for j in range(img2.shape[1]):
        img2[i][j]=[random.randint(0,255),random.randint(0,255),random.randint(0,255)]

In [21]:
cv2.imshow("Image",img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 4) copy n pasting part of an image

In [22]:
# if you want to double the size then fx=2,fy=2 and if half then fx=0.5,fy=0.5
img4=cv2.resize(img3,(0,0),fx=0.7,fy=0.7)
cv2.imshow("Image1",img4)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
img4.shape

(557, 557, 3)

In [26]:
tag=img4[200:350,200:350]
img4[0:150,0:150]=tag # dimension should be same

In [27]:
cv2.imshow("Image1",img4)
cv2.waitKey(0)
cv2.destroyAllWindows()